---
- include_tasks: apache2.yml
  when: ansible_cloudflare_server == "apache2"
  tags:
    - cloudflare

- include_tasks: nginx.yml
  when: ansible_cloudflare_server == "nginx"
  tags:
    - cloudflare

